website/views.py
from flask import Blueprint, render_template, jsonify, session, redirect, url_for, flash, request
from markupsafe import re
from .auth import is_logged_in, is_admin
import random
from .database import *
from bson.objectid import ObjectId


views = Blueprint('views', __name__)


@views.route('/api')
def api():
    c = random.random()
    return jsonify({'data': f'{c}'})


@views.route('/')
def index():
    return render_template('index.html')


def evaluation_duration(course):
    """calculates & returns the appropriate time to be spent in evaluating"""
    _questions = [question for question in questions.find({"course": course})]
    duration = len(_questions) * 15
    time = f"{duration} secs"

    if duration > 60:
        mins = int(duration / 60)
        mins_text = f"{mins} min" if mins == 1 else f"{mins} mins"
        secs = duration - (60 * mins)
        secs_text = "" if secs == 0 else f"{secs} secs"

        time = f"{mins_text} {secs_text} "

    return time

  

@views.route('/dashboard')
@is_logged_in
def dashboard():

    if session['usertype'] == 'student':
        account = students.find_one({"regnumber": session['regnumber']})

        query = [{"level": account['level']}, 
                 {"open_for_evaluation": 'true'}]

        courses_query = [course for course in courses.find({"$and": query})]
        courses_offered = [course for course in courses_query if course['course'] not in account['courses_evaluated']]

        courses_evaluated = [course for course in courses_query if course['course'] in account['courses_evaluated']]

        
        return render_template('dashboard.html', account=account,
                                courses_offered=courses_offered,
                                courses_evaluated=courses_evaluated,
                                evaluation_duration=evaluation_duration)
    
    elif session['usertype'] == 'lecturer':
        account = lecturers.find_one({"username": session['username']})
        courses_taught = [course_taught for course_taught in courses.find() if account['_id'] == ObjectId(course_taught['lecturer'])]
        
        return render_template('lecturer/lecturer_dashboard.html', courses_taught=courses_taught, questions=questions)

    elif session['usertype'] == 'admin':
        return render_template('admin/dashboard.html')

    else:
        flash('Sorry, You cannot access this page.')
        return redirect(url_for('auth.login'))


@views.route('/recover_password')
def recover_password():
    return render_template('recover_password.html')


@views.route('/profile')
@is_logged_in
def profile():
    collection = db[f"{session['usertype']}s"]
    user_found = collection.find_one({"regnumber": session["regnumber"]}) if session['usertype'] == 'student' else collection.find_one({"username": session["username"]})
    return render_template('profile.html', user_found=user_found)


@views.route('/settings')
@is_admin
def settings(): 
    data = {}
    data['sessions'] = [session for session in sessions.find()]
    data['levels'] = [level for level in levels.find()]
    data['semesters'] = [semester for semester in semesters.find()]
    data['positions'] = [position for position in positions.find()]
    data['states'] = [state for state in states.find()]
    print(data)
    return render_template('admin/settings.html', data=data)


@views.route('/manage_lecturers')
@is_admin
def manage_lecturers():
    lecturer = [lecturer for lecturer in lecturers.find()]
    position = [position for position in positions.find().sort('position')]
    return render_template('admin/manage_lecturers.html', lecturers=lecturer, positions=position)


def find_lecturer(id):
    """
        Returns a lecturer found
    """
    lecturer = lecturers.find_one({"_id": id})
    return lecturer if lecturer is not None else 'None'


@views.route('/manage_courses')
@is_admin
def manage_courses():
    lecturer_list = [lecturer for lecturer in lecturers.find()]
    level_list = [level for level in levels.find()]
    semester_list = [semester for semester in semesters.find()]
    course_list = [course for course in courses.find()]

    print(lecturer_list)
    return render_template('admin/manage_courses.html',
                            find_lecturer=find_lecturer,
                            lecturers=lecturer_list,
                            levels=level_list,
                            semesters=semester_list,
                            courses=course_list,
                            ObjectId=ObjectId)


@views.route('/manage_students')
def manage_students():
    student_list = []
    studs = {}
    level_list = [level for level in levels.find()]

    for level in level_list:
        student_list = [student for student in students.find({'level': level['level']})]
        studs[f"{level['level']}"] = student_list
        student_list = []
    


    for stud in studs:
        print(f'{stud}:', studs[stud])

    

    return render_template('admin/manage_students.html', studs=studs, levels=level_list)


@views.route('/user/<id>')
def user(id): 
    return render_template('users.html', id=id)

@views.route('/evaluate/<string:id>')
@is_logged_in
def evaluate(id):
    course = courses.find_one({"course": id})
    student = students.find_one({"regnumber": session['regnumber']})

    if student['level'] != course['level']:
        flash("You have no business evaluating this course", 'warning')
        return redirect(url_for('views.dashboard'))

    if course['open_for_evaluation'] == 'false':
        flash(f"Course '{id}' is not open for evaluation", 'warning')
        return redirect(url_for('views.dashboard'))

    course_lecturer = lecturers.find_one({"_id": ObjectId(course['lecturer'])})
    question_list = [question for question in questions.find({"course": id, "activated": 'true'})]

    
    return render_template('evaluate.html', id=id, question_list=question_list, course=course,
                            course_lecturer=course_lecturer)
 

@views.route('evaluation_result')
@is_admin
def evaluation_result():
    
    return render_template('admin/evaluation_result.html')


@views.route('/evaluation_stats', methods=['GET'])
@is_admin
def evaluation_stats():

    level_list = [ level for level in levels.find() ]
    data = {}

    for level in level_list:

        course_list = [ course for course in courses.find({"level": level['level']}) ]
        title = f"{level['class']} stats - BarChart"
        data100, data75, data50, data25, _course = [], [], [], [], []
        # def calc_per(total)

        calc_per = lambda total, single: float(f"{single / total * 100:.2f}")


        for course in course_list:

            x = course['scores']
            num100, num75, num50, num25 = x['100'] + 1, x['75'] + 1, x['50'] + 1, x['25'] + 1

            # accuired_score = sum([num100 * 100, num75 , num50, num25])
            # division error

            expected_score = sum([num100, num75, num50, num25])
            print(expected_score)

            data100.append( calc_per(expected_score, num100) )
            data75.append( calc_per(expected_score, num75) )
            data50.append( calc_per(expected_score, num50) )
            data25.append( calc_per(expected_score, num25) )
            _course.append(course['course'])

        data[f"level{level['level']}"] = {
                                "title": title,
                                "courses": _course,
                                "data100": data100, 
                                "data75": data75, 
                                "data50": data50, 
                                "data25": data25, 
                                }

    print(data, course_list)
    
    return jsonify(data)




    

website/templates/_test.html
<div>
  <ul>
  {% for student in student_data %}
     🔹{{ student.course }} - {{ student.code|capitalize }} <br>
  {% endfor %}
  </ul>
</div>

website/templates/courses.html
{% extends 'layout.html' %}
{% block title %} Courses {% endblock %}}

{% block body %}

	{% include 'includes/_navbar.html' %}
			
	{% include 'includes/_sidebar.html' %}

    

{% endblock %}

website/templates/dashboard.html
{% extends 'layout.html' %} {% block title %}Dashboard{% endblock %} {% block
body%} {% include 'includes/_navbar.html' %} {% include
'includes/_sidebar.html'%}

<div class="app-content content container-flid">
	<div class="content-wrapper">
		<div class="content-header row">
			<div class="content-header-left col-xs-12 mb-1">
				<h2 class="content-header-title">Welcome {{session['username']}}</h2>
				<span>Select a course to evaluate.</span>
				<hr />
			</div>
			<div
				class="content-header-right breadcrumbs-right breadcrumbs-top col-md-6 col-xs-12"
			>
				{% include 'includes/_messages.html' %}
			</div>
		</div>

		<div class="content-body">
			<div class="row container">
				{% set base_color = ['primary', 'success', 'info', 'pink', 'purple',
				'indigo', 'cyan', 'teal', 'green', 'yellow', 'amber', 'brown', 'grey']
				%} {% if courses_offered|count > 0 %} {% for course in courses_offered
				%}

				<div class="col-xl-4 col-lg-6 col-sm-6 col-xs-12">
					<a href="{{ url_for('views.evaluate', id=course['course'] )}}">
						<div class="card">
							<div class="card-body">
								<div class="card-block">
									<div class="media">
										<div class="media-left media-middle">
											<i
												class="icon-stats-bars2 {{base_color[loop.index - 1]}} font-large-2 float-xs-left"
											></i>
										</div>
										<div class="media-body text-xs-right">
											<h3 class="{{base_color[loop.index - 1]}} darken-2">
												{{course['course']}}
											</h3>
											<span class="grey darken-1">
												Approx. {{ evaluation_duration(course['course'])}}
											</span>
										</div>
									</div>
								</div>
							</div>
						</div>
					</a>
				</div>

				{% endfor %} {% else %}

				<div class="jumbotron text-sm-center container">
					There is no course for you to evaluate. Please check back later.
				</div>

				{% endif %}
			</div>

			<div>
				<h4>Courses evaluated</h4>
				<hr />
			</div>

			<div class="row container">
				{% if courses_evaluated|length > 0 %} {% for course in courses_evaluated
				%}
				<div class="col-xl-4 col-lg-6 col-sm-6 col-xs-12">
					<div class="card">
						<div class="card-body">
							<div class="card-block">
								<div class="media">
									<div class="media-left media-middle">
										<i class="icon-check grey font-large-2 float-xs-left"></i>
									</div>
									<div class="media-body text-xs-right">
										<h3 class="grey darken-2">{{course['course']}}</h3>
										<span class="grey"
											>Evaluated
											[{{course['scores']['no_of_evaluation']}}]</span
										>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				{% endfor %} {% else %}
				<div class="jumbotron text-sm-center container">
					You have not evaluated any courses!
				</div>
				{% endif %}
			</div>
		</div>
	</div>
</div>

<!-- <script>
        window.setInterval(function() {
        fetch('/api')
        .then(function(response){
            return response.json();
        })
        .then(function(myJson){
            document.getElementById('display').innerHTML = myJson['data'];
        })
    }, 2000)
    </script> -->
{% endblock %}

website/templates/evaluate.html
{% extends 'layout.html' %} {% block title %}Dashboard{% endblock %} {% block
body%} {% include 'includes/_navbar.html' %} {% include
'includes/_sidebar.html'%}
{% include 'includes/_messages.html' %}

<div class="app-content content container-fluid">
	<div class="content-wrapper">
		<div class="content-header row">

			<div class=" col-md-6 col-xs-12 ">
				<h2 class="content-header-title">COURSE: {{ id }}</h2>
				<span>{{ question_list|length }} Question(s)</span>
			</div>

			<div class=" col-md-6 col-xs-12">
        <span class="float-xs-right">
          Lecturer: <b>{{ course_lecturer['firstname']|title }} {{ course_lecturer['lastname']|title  }}</b>
        </span><br> 
        <span class="float-xs-right">Position: <b>{{ course_lecturer['position']|title }} </b></span>
			</div>
      
		</div>

    <hr>

		<div class="content-body">

			<form action="{{ url_for('auth.evaluation_sum') }}" method="post">
        <input type="hidden" name="course" value="{{ course['course'] }}" />
          {% for question in question_list %}  
          <div class="container mb-2 card py-1 card-body">

            <span class="font-medium-2 text-bold-600">
              {{ loop.index }}. &nbsp; {{ question['question']|title }} <br>
            </span>

            <div class=" ml-3 container row mt-1">

            {% for option in question['options'] %}              
              <div class="check col-sm-6 mb-1">
                <input class="form-check-input " type="radio" name="{{ question['question'] }}" value="{{ question['options'][option] }}" id="{{ question['question'] }}{{ loop.index }}">
                <label class="form-check-label" for="{{ question['question'] }}{{ loop.index }}"
                        style="padding-left: 5px">
                  {{ option|title }}
                </label>
              </div>
            {% endfor %}

            </div>
          </div>

          {% endfor %}
          <div class="container" align="center">
            <button class="btn btn-primary btn-large half-width" type="submit" value="">
              Submit
            </button>
          </div>
      </form>

		</div>
	</div>
</div>

<!-- <script>
        window.setInterval(function() {
        fetch('/api')
        .then(function(response){
            return response.json();
        })
        .then(function(myJson){
            document.getElementById('display').innerHTML = myJson['data'];
        })
    }, 2000)
    </script> -->
{% endblock %}

website/templates/index.html
{% extends 'layout.html' %}

<!-- title -->
{% block title %}Course Evaluation{% endblock %}

<!-- body -->
{% block body%} {% include 'includes/_navbar_index.html' %}
<div class="mb-3"></div>
<div class=" container-fluid">
	<div class="card mt-5">
		<div class="card-header">
			<h4 class="card-title">Basic Example</h4>
		</div>
		<div class="card-body collapse in">
			<div class="card-block">
				<div
					id="carousel-example-generic"
					class="carousel slide"
					data-ride="carousel"
				>
					<ol class="carousel-indicators">
						<li
							data-target="#carousel-example-generic"
							data-slide-to="0"
							class="active"
						></li>
						<li data-target="#carousel-example-generic" data-slide-to="1"></li>
						<li data-target="#carousel-example-generic" data-slide-to="2"></li>
					</ol>
					<div class="carousel-inner" role="listbox">
						<div class="carousel-item active">
							<img
								src="../../static/app-assets/images/carousel/02.jpg"
								alt="First slide"
							/>
						</div>
						<div class="carousel-item">
							<img
								src="../../static/app-assets/images/carousel/03.jpg"
								alt="Second slide"
							/>
						</div>
						<div class="carousel-item">
							<img
								src="../../static/app-assets/images/carousel/01.jpg"
								alt="Third slide"
							/>
						</div>
					</div>
					<a
						class="left carousel-control"
						href="#carousel-example-generic"
						role="button"
						data-slide="prev"
					>
						<span class="icon-prev" aria-hidden="true"></span>
						<span class="sr-only">Previous</span>
					</a>
					<a
						class="right carousel-control"
						href="#carousel-example-generic"
						role="button"
						data-slide="next"
					>
						<span class="icon-next" aria-hidden="true"></span>
						<span class="sr-only">Next</span>
					</a>
				</div>
			</div>
		</div>
	</div>
</div>	

{% include 'includes/_footer.html' %} {% endblock %}

website/templates/layout.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>{% block title%} {% endblock %}</title>

		{% include "includes/_csslinks.html" %}
	</head>
	<body
		data-open="click"
		data-menu="vertical-menu"
		data-col="2-columns"
		class="vertical-layout vertical-menu 2-columns fixed-navbar"
	>
		

		<!-- {% include 'includes/_messages.html' %} -->

		{% block body %} {% include "includes/_footer.html" %} {% endblock %} {%
		include "includes/_jslinks.html" %}
	</body>
</html>

website/templates/login.html
{% extends 'layout.html' %} {% block title %}Login{% endblock %} {% block body%}
<!-- {% if message%}
            {{message}}
        {% endif %} -->

<div class="app-content container-fluid" style="margin-left: 0px !important">
	<div class="content-wrapper">
		<div class="content-header row"></div>

		<div class="content-body">
			<section class="flexbox-container">
				<div
					class="col-md-4 offset-md-4 col-xs-10 offset-xs-1 box-shadow-2 p-0"
				>
					<div class="card border-grey border-lighten-3 m-0">
						<div class="card-header no-border">
							<div class="card-title text-xs-center">
								<div class="p-1">
									<a href="/"
										><img
											src="../static/app-assets/images/logo/robust-logo-dark.png"
											alt="branding logo"
									/></a>
								</div>
							</div>
							<h6
								class="card-subtitle line-on-side text-muted text-xs-center font-small-3 pt-2"
							>
								<span>Login with Robust</span>
							</h6>
						</div>

						<div class="card-body collapse in">
							<div class="card-block">
								<form
									class="form-horizontal form-simple"
									method="post"
									action="/login"
									validate
								>
									<div style="margin-top: 0px">
										{% include 'includes/_messages.html' %}
									</div>
									<fieldset
										class="form-group position-relative has-icon-left mb-0"
									>
										<input
											type="text"
											class="form-control form-control-lg input-lg"
											name="username"
											id="user-name"
											placeholder="Username / RegNo (20/1212)"
											value="{{request.form.username}}"
											required
										/>
										<div class="form-control-position">
											<i class="icon-head"></i>
										</div>
									</fieldset>
									<br />
									<fieldset class="form-group position-relative has-icon-left">
										<input
											type="password"
											class="form-control form-control-lg input-lg"
											name="password"
											id="user-password"
											placeholder="Enter Password"
											autocomplete="off"
											required
										/>
										<div class="form-control-position">
											<i class="icon-key3"></i>
										</div>
									</fieldset>
									<fieldset class="form-group row">
										<div class="col-md-6 col-xs-12 text-xs-center text-md-left">
											<fieldset>
												<input
													type="checkbox"
													id="remember-me"
													class="chk-remember"
												/>
												<label for="remember-me"> Remember Me</label>
											</fieldset>
										</div>
										<div
											class="col-md-6 col-xs-12 text-xs-center text-md-right"
										>
											<a href="/recover_password" class="card-link"
												>Forgot Password?</a
											>
										</div>
									</fieldset>
									<button
										type="submit"
										class="btn btn-primary btn-lg btn-block"
									>
										<i class="icon-unlock2"></i> Login
									</button>
								</form>
							</div>
						</div>

						<div class="card-footer">
							<div class="">
								<p class="float-sm-left text-xs-center m-0">
									<a href="/recover_password" class="card-link"
										>Recover password</a
									>
								</p>
								<p class="float-sm-right text-xs-center m-0">
									New to Robust?
									<a href="/register" class="card-link">Sign Up</a>
								</p>
							</div>
						</div>
					</div>
				</div>
			</section>
		</div>
	</div>
</div>
{% endblock %}

website/templates/profile.html
{% extends 'layout.html' %}
{% block title %} Profile | {{session.username.title()}} {% endblock %}}

{% block body %}

	{% include 'includes/_navbar.html' %}
			
	{% include 'includes/_sidebar.html' %}

	<div class="app-content content container-fluid">
		<div class="content-wrapper">

			<div class="row match-height">
				<div class="col-xl-4 col-lg-12">
					<div class="card card-inverse bg-cyan">
       <div class="card-body">
                            
						</div>
					</div>
				</div>
				<div class="col-xl-8 col-lg-12">
					<div class="card">
						<div class="card-header">                         

										<!-- Pills Toggle Buttons -->
										<ul class="nav nav-pills">
														<li class="nav-item">
																		<a class="nav-link " id="base-pill1" data-toggle="pill" href="#pill1" aria-expanded="true"><strong>Profile</strong></a>
														</li>
														<li class="nav-item">
																		<a class="nav-link active" id="base-pill2" data-toggle="pill" href="#pill2" aria-expanded="false"><strong>Edit Profile</strong></a>
														</li>
														<li class="nav-item">
																		<a class="nav-link " id="base-pill3" data-toggle="pill" href="#pill3" aria-expanded="false"><strong>Password</strong></a>
														</li>
										</ul>

										<a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
										<div class="heading-elements">
														<ul class="list-inline mb-0">
																		<li><a data-action="expand"><i class="icon-expand2"></i></a></li>
														</ul>
										</div>
						</div>
							<div class="card-body collapse in">
								<div class="card-block">
										<div class="tab-content  pt-">

											<div role="tabpanel" class="tab-pane " id="pill1" aria-expanded="true" aria-labelledby="base-pill1">
															<p>Oat cake marzipan cake lollipop caramels wafer pie jelly beans. Icing halvah chocolate cake carrot cake. Jelly beans carrot cake marshmallow gingerbread chocolate cake. Gummies cupcake croissant.</p>
											</div>

											<div class="tab-pane active" id="pill2" aria-labelledby="base-pill2">
															
															<form class="form" method="post" action="/update_profile">
																			<div class="form-body">
																							<h4 class="form-section"><i class="icon-head"></i> Personal Info</h4>
																							<div class="row">
																											<div class="col-md-6 col-xl-4">
																															<div class="form-group">
																																			<div class="position-relative has-icon-left">
																																							<input type="text" id="" class="form-control" placeholder="First Name" name="firstname" value="{{user_found.firstname.title()}}">
																																							<div class="form-control-position">
																																											<i class="icon-head"></i>
																																							</div>
																																			</div>
																															</div>
																											</div>
																											<div class="col-md-6 col-xl-4">
																															<div class="form-group">
																																			<div class="position-relative has-icon-left">
																																							<input type="text" id="projectinput2" class="form-control" placeholder="Last Name" name="lastname" value="{{user_found['lastname'].title()}}">
																																							<div class="form-control-position">
																																											<i class="icon-head"></i>
																																							</div>
																																			</div>
																															</div>
																											</div>
																											<div class="col-md-6 col-xl-4">
																															<div class="form-group">
																																			<div class="position-relative has-icon-left">
																																							<input type="text" id="projectinput2" class="form-control" readonly placeholder="Username" name="username" value="{{session.username.title()}}">
																																							<div class="form-control-position">
																																											<i class="icon-head"></i>
																																							</div>
																																			</div>
																															</div>
																											</div>
																											
																											<div class="col-md-6 col-xl-4">
																															<div class="form-group">
																																			
																																			<div class="position-relative has-icon-left">
																																							<select id="projectinput5" name="gender" class="form-control" selected="{{user_found.gender}}">
																																											<option value="none" {% if user_found.gender == 'none' %}selected=""{% endif %} disabled="">Gender</option>
																																											<option value="male" {% if user_found.gender == 'male' %}selected=""{% endif %} >Male</option>
																																											<option value="female" {% if user_found.gender == 'female' %}selected=""{% endif %}>Female</option>
																																							</select>
																																							<div class="form-control-position">
																																											<i class="icon-male"></i>
																																							</div>
																																			</div>
																															</div>
																											</div>
																							</div>

																							<h4 class="form-section"><i class="icon-email3"></i> Contact Info & Bio</h4>

																						<div class="row mb-0">
																											<div class="col-md-6 col-xl-4">
																															<div class="form-group">
																																			<div class="position-relative has-icon-left">
																																							<input type="text" id="projectinput4" class="form-control" value="{{user_found.phone}}" placeholder="Phone" name="phone">
																																							<div class="form-control-position">
																																											<i class="icon-mobile-phone"></i>
																																							</div>
																																			</div>
																															</div>
																											</div>

																											<div class="col-md-6 col-xl-4">
																															<div class="form-group">
																																			<div class="position-relative has-icon-left">
																																							<input type="text" id="projectinput3" class="form-control" value="{{user_found.email}}" placeholder="E-mail" name="email">
																																							<div class="form-control-position">
																																											<i class="icon-email2"></i>
																																							</div>
																																			</div>
																															</div>
																											</div>
																											<div class="col-xs-12 mb-0">
																															<div class="form-group">
																																			<div class="position-relative has-icon-left">
																																							<textarea id="timesheetinput7" rows="5" class="form-control" name="about" placeholder="About me">{{user_found.about.capitalize()}}</textarea>
																																							<div class="form-control-position">
																																											<i class="icon-file2"></i>
																																							</div>
																																			</div>
																															</div>
																											</div>
																			</div>
																			</div>
																			<div class=" col-sm-8">
																			</div>
																			<button type="submit" class="btn btn-primary col-xs-12 col-sm-4 ">
																							<i class="icon-check2"></i> Save
																			</button>
															</form>
											</div>

											<div role="tabpanel" class="tab-pane " id="pill3" aria-expanded="true" aria-labelledby="base-pill3">
															{% include 'includes/_messages.html' %}
															<form class="form" method="post" action="/update_password">
																			<div class="form-body">
																							<h4 class="form-section"><i class="icon-unlock2"></i> Password</h4>
																							<div class="row">
																											<div class="col-md-6 col-xl-4">
																															<div class="form-group">
																																			<div class="position-relative has-icon-left">
																																							<input type="password" id="" class="form-control" required placeholder="Old password" name="opassword">
																																							<div class="form-control-position">
																																											<i class="icon-unlock2"></i>
																																							</div>
																																			</div>
																															</div>
																											</div>
																											<div class="col-md-6 col-xl-4">
																															<div class="form-group">
																																			<div class="position-relative has-icon-left">
																																							<input type="password" id="projectinput2" class="form-control" required placeholder="New password" name="npassword">
																																							<div class="form-control-position">
																																											<i class="icon-lock4"></i>
																																							</div>
																																			</div>
																															</div>
																											</div>
																											<div class="col-md-6 col-xl-4">
																															<div class="form-group">
																																			<div class="position-relative has-icon-left">
																																							<input type="password" id="projectinput2" class="form-control" required placeholder="Confirm new password" name="cnpassword">
																																							<div class="form-control-position">
																																											<i class="icon-lock4"></i>
																																							</div>
																																			</div>
																															</div>
																											</div>
																							</div>
																			</div>
																			<div class=" col-sm-8">
																			</div>
																			<button type="submit" class="btn btn-primary col-xs-12 col-sm-4 ">
																							<i class="icon-check2"></i> Save
																			</button>
															</form>
											</div>
										</div>
								</div>
							</div>
					</div>
				</div>
			</div>

		</div>
	</div>
{% endblock %}
 

website/templates/test.html
{% extends 'layout.html' %}
{% block body %}
  <div class="container">

    <h1>Welcome</h1>
    <p id="data"></p>
  
    <a  id="btn" class="btn btn-primary">Magic</a>
  </div> 



<script src="../static/js/jquery-2.1.4.min.js" type="text/javascript"></script>
<script>
  $("#btn").click(function() {
    
    $.ajax({
      url: "/tester",
      type: "GET",
      success: function(response){
        $("#data").html(response);
      },
    });
  });
</script>

{% endblock %}