website/auth.py
from re import L
from flask import Blueprint, render_template, session, request, flash, redirect, url_for, jsonify
from functools import wraps
from .database import *
import datetime
from bson.objectid import ObjectId
import random


dt = datetime.datetime.now()
date_now = dt.strftime('%A-%d-%b-%Y  %I:%M %p')

# Creating collection

auth = Blueprint('auth', __name__)


# Permission Decorator
def is_logged_in(f):
    @wraps(f)
    def wrap(*args, **kwargs): 
        if 'logged_in' in session:
            return f(*args, **kwargs)
        else: 
            flash('Unauthorized Access!', 'danger')
            return redirect(url_for('auth.login'))
    return wrap


def is_admin(f):
    @wraps(f)
    def wrap(*args, **kwargs): 
        if 'logged_in' in session:
            if session['usertype'] == 'admin':
                return f(*args, **kwargs)

            flash('Unauthorized Access! ❌', 'danger')
            return redirect(url_for('views.dashboard'))
        else: 
            flash('Unauthorized Access!', 'danger')
            return redirect(url_for('auth.login'))
    return wrap


def is_lecturer(f):
    @wraps(f)
    def wrap(*args, **kwargs): 
        if 'logged_in' in session:
            if session['usertype'] == 'lecturer' or session['usertype'] == 'admin':
                return f(*args, **kwargs)

            flash('Only a lecturer can access this page', 'danger')
            return redirect(url_for('views.dashboard'))
        else: 
            flash('Unauthorized Access!', 'danger')
            return redirect(url_for('auth.login'))
    return wrap



# ALL AUTHENTICATIONS ARE DONE HERE
@auth.route('/login', methods=['GET', 'POST'])
def login():

    if 'username' in session:
        flash('You are already logged in!', 'success')
        return redirect(url_for('views.dashboard'))
    
    if request.method == 'POST':
        username = request.form['username'].lower()
        password = request.form['password']

        account = students.find_one({"regnumber": username})
        lecturer_account = lecturers.find_one({"username": username})
        admin_account = admins.find_one({"username": username})
        print(admin_account)

        if account:
            print(account)
            if account['password'] == password:
                session['logged_in'] = True 
                session['username'] = account['firstname'] + " " + account['lastname']
                session['regnumber'] = account['regnumber']
                session['usertype'] = "student"
                return redirect(url_for('views.dashboard'))
            else: 
                flash('Invalid login details!', 'danger')
                return render_template('login.html')

        elif admin_account:
            if admin_account["password"] == password:
                session['logged_in'] = True
                session['username'] = username
                session['usertype'] = "admin"
                return redirect(url_for('views.dashboard'))
            else: 
                flash('Invalid login details!', 'danger')
                return render_template('login.html')


        elif lecturer_account:
            if lecturer_account["password"] == password:
                session['logged_in'] = True
                session['username'] = username
                session['usertype'] = "lecturer"
                return redirect(url_for('views.dashboard'))
            else:
                flash('Invalid login details', 'warning')
                return render_template('login.html')

        else: 
            flash('Account does not exists. Please Login', 'danger')
            return render_template('login.html')

    return render_template('login.html')


@auth.route('/logout')
def logout(): 
    session.clear()
    flash('You are now logged out!', 'success')
    return redirect(url_for('auth.login'))


@auth.route('/register', methods=['POST', 'GET'])
def register():

    if request.method == 'POST':
        firstname = request.form.get('firstname').title()
        lastname = request.form.get('lastname').title()
        regnumber = request.form.get('regnumber').upper()
        phone = request.form.get('phone')
        email = request.form.get('email').lower()
        gender = request.form.get('gender').lower()
        level = request.form.get('level')
        pic = request.form.get('pic')
        password = request.form.get('password')
        cpassword = request.form.get('cpassword')


        try: # save to database
            if password == cpassword: 
                if students.find_one({"regnumber":regnumber}) or students.find_one({"phone":phone}) or students.find_one({"email":email}):
                    flash('Account exists!', 'danger')
                    return render_template('register.html')

                else:
                    student = {
                        'firstname': firstname, 
                        'lastname': lastname, 
                        'gender': gender, 
                        'regnumber': regnumber, 
                        'phone': phone, 
                        'email': email, 
                        'password': password,
                        'level': level,
                        'pic': pic,
                        'about': '',
                        'date_created': date_now}

                    students.insert_one(student)
                                                    
                    flash('Account created', 'success')
                    return render_template('register.html')
            
            flash('Passwords do not match!', 'danger')
            return render_template('register.html')

        except Exception as e: 
            flash('Something went wrong. Please try again.', 'danger')
            return render_template('register.html')

    return render_template('register.html')


@auth.route('/add_student', methods=['POST'])
def add_student():

    if request.method == 'POST':
        firstname = request.form.get('firstname').title()
        lastname = request.form.get('lastname').title()
        regnumber = request.form.get('regnumber').upper()
        phone = request.form.get('phone')
        email = request.form.get('email').lower()
        gender = request.form.get('gender').lower()
        level = request.form.get('level')
        pic = request.form.get('pic')
        password = request.form.get('password')
        cpassword = request.form.get('cpassword')


        try: # save to database
            if password == cpassword: 
                if students.find_one({"regnumber":regnumber}) or students.find_one({"phone":phone}) or students.find_one({"email":email}):
                    flash('Account exists!', 'danger')
                    return redirect(url_for('views.manage_students'))

                else:
                    student = {
                        'firstname': firstname, 
                        'lastname': lastname, 
                        'gender': gender, 
                        'regnumber': regnumber, 
                        'phone': phone, 
                        'email': email, 
                        'password': password,
                        'level': level,
                        'pic': pic,
                        'about': '',
                        'date_created': date_now, 
                        'courses_evaluated':[]}

                    students.insert_one(student)
                                                    
                    flash('Account created!', 'success')
                    return redirect(url_for('views.manage_students'))
            
            flash('Passwords do not match!', 'danger')
            return redirect(url_for('views.manage_students'))

        except Exception as e: 
            flash('Something went wrong. Please try again.', 'danger')
            return redirect(url_for('views.manage_students'))

    return redirect(url_for('views.manage_students'))


@auth.route('/update_student', methods=['GET', 'POST'])
def update_student():
    if request.method == 'POST':

        _id = request.form.get('_id')
        firstname = request.form.get('firstname').title()
        lastname = request.form.get('lastname').title()
        regnumber = request.form.get('regnumber').upper()
        phone = request.form.get('phone')
        email = request.form.get('email').lower()
        level = request.form.get('level')
        password = request.form.get('password')
        cpassword = request.form.get('cpassword')

        candidate = students.find_one({"_id": ObjectId(_id)})

        try:
            if password == cpassword:
                students.update_one(
                    {"_id": ObjectId(_id)},[
                    {"$set": {"regnumber": regnumber}},
                    {"$set": {"firstname": firstname}},
                    {"$set": {"lastname": lastname}},
                    {"$set": {"email": email}},
                    {"$set": {"phone": phone}},
                    {"$set": {"level": level}},
                    {"$set": {"password": password}},
                    {"$set": {"date_last_updated": date_now}}]
                )
                flash('Student Record Updated!', 'success')
                return redirect(url_for('views.manage_students'))

            flash('Passwords have to be the same', 'danger')
            return redirect(url_for('views.manage_students'))

        except:
            flash('An error occurred! Please try again later.', 'danger')
            return redirect(url_for('views.manage_students'))

    return redirect(url_for('views.manage_students'))


@auth.route('/update_profile', methods=['POST'])
@is_logged_in
def update_profile():
    if request.method == 'POST':
        username = request.form.get('username').lower()
        firstname = request.form.get('firstname').lower()
        lastname = request.form.get('lastname').lower()
        email = request.form.get('email').lower()
        phone = request.form.get('phone')

website/views.py
from flask import Blueprint, render_template, jsonify, session, redirect, url_for, flash, request
from markupsafe import re
from .auth import is_logged_in, is_admin
import random
from .database import *
from bson.objectid import ObjectId


views = Blueprint('views', __name__)


@views.route('/api')
def api():
    c = random.random()
    return jsonify({'data': f'{c}'})


@views.route('/')
def index():
    return render_template('index.html')


def evaluation_duration(course):
    """calculates & returns the appropriate time to be spent in evaluating"""
    _questions = [question for question in questions.find({"course": course})]
    duration = len(_questions) * 15
    time = f"{duration} secs"

    if duration > 60:
        mins = int(duration / 60)
        mins_text = f"{mins} min" if mins == 1 else f"{mins} mins"
        secs = duration - (60 * mins)
        secs_text = "" if secs == 0 else f"{secs} secs"

        time = f"{mins_text} {secs_text} "

    return time

  

@views.route('/dashboard')
@is_logged_in
def dashboard():

    if session['usertype'] == 'student':
        account = students.find_one({"regnumber": session['regnumber']})

        query = [{"level": account['level']}, 
                 {"open_for_evaluation": 'true'}]

        courses_query = [course for course in courses.find({"$and": query})]
        courses_offered = [course for course in courses_query if course['course'] not in account['courses_evaluated']]

        courses_evaluated = [course for course in courses_query if course['course'] in account['courses_evaluated']]

        
        return render_template('dashboard.html', account=account,
                                courses_offered=courses_offered,
                                courses_evaluated=courses_evaluated,
                                evaluation_duration=evaluation_duration)
    
    elif session['usertype'] == 'lecturer':
        account = lecturers.find_one({"username": session['username']})
        courses_taught = [course_taught for course_taught in courses.find() if account['_id'] == ObjectId(course_taught['lecturer'])]
        
        return render_template('lecturer/lecturer_dashboard.html', courses_taught=courses_taught, questions=questions)

    elif session['usertype'] == 'admin':
        return render_template('admin/dashboard.html')

    else:
        flash('Sorry, You cannot access this page.')
        return redirect(url_for('auth.login'))


@views.route('/recover_password')
def recover_password():
    return render_template('recover_password.html')


@views.route('/profile')
@is_logged_in
def profile():
    collection = db[f"{session['usertype']}s"]
    user_found = collection.find_one({"regnumber": session["regnumber"]}) if session['usertype'] == 'student' else collection.find_one({"username": session["username"]})
    return render_template('profile.html', user_found=user_found)


@views.route('/settings')
@is_admin
def settings(): 
    data = {}
    data['sessions'] = [session for session in sessions.find()]
    data['levels'] = [level for level in levels.find()]
    data['semesters'] = [semester for semester in semesters.find()]
    data['positions'] = [position for position in positions.find()]
    data['states'] = [state for state in states.find()]
    print(data)
    return render_template('admin/settings.html', data=data)


@views.route('/manage_lecturers')
@is_admin
def manage_lecturers():
    lecturer = [lecturer for lecturer in lecturers.find()]
    position = [position for position in positions.find().sort('position')]
    return render_template('admin/manage_lecturers.html', lecturers=lecturer, positions=position)


def find_lecturer(id):
    """
        Returns a lecturer found
    """
    lecturer = lecturers.find_one({"_id": id})
    return lecturer if lecturer is not None else 'None'


@views.route('/manage_courses')
@is_admin
def manage_courses():
    lecturer_list = [lecturer for lecturer in lecturers.find()]
    level_list = [level for level in levels.find()]
    semester_list = [semester for semester in semesters.find()]
    course_list = [course for course in courses.find()]

    print(lecturer_list)
    return render_template('admin/manage_courses.html',
                            find_lecturer=find_lecturer,
                            lecturers=lecturer_list,
                            levels=level_list,
                            semesters=semester_list,
                            courses=course_list,
                            ObjectId=ObjectId)


@views.route('/manage_students')
def manage_students():
    student_list = []
    studs = {}
    level_list = [level for level in levels.find()]

    for level in level_list:
        student_list = [student for student in students.find({'level': level['level']})]
        studs[f"{level['level']}"] = student_list
        student_list = []
    


    for stud in studs:
        print(f'{stud}:', studs[stud])

    

    return render_template('admin/manage_students.html', studs=studs, levels=level_list)


@views.route('/user/<id>')
def user(id): 
    return render_template('users.html', id=id)

@views.route('/evaluate/<string:id>')
@is_logged_in
def evaluate(id):
    course = courses.find_one({"course": id})
    student = students.find_one({"regnumber": session['regnumber']})

    if student['level'] != course['level']:
        flash("You have no business evaluating this course", 'warning')
        return redirect(url_for('views.dashboard'))

    if course['open_for_evaluation'] == 'false':
        flash(f"Course '{id}' is not open for evaluation", 'warning')
        return redirect(url_for('views.dashboard'))

    course_lecturer = lecturers.find_one({"_id": ObjectId(course['lecturer'])})
    question_list = [question for question in questions.find({"course": id, "activated": 'true'})]

    
    return render_template('evaluate.html', id=id, question_list=question_list, course=course,
                            course_lecturer=course_lecturer)
 

@views.route('evaluation_result')
@is_admin
def evaluation_result():
    
    return render_template('admin/evaluation_result.html')


@views.route('/evaluation_stats', methods=['GET'])
@is_admin
def evaluation_stats():

    level_list = [ level for level in levels.find() ]
    data = {}

    for level in level_list:

        course_list = [ course for course in courses.find({"level": level['level']}) ]
        title = f"{level['class']} stats - BarChart"
        data100, data75, data50, data25, _course = [], [], [], [], []
        # def calc_per(total)

        calc_per = lambda total, single: float(f"{single / total * 100:.2f}")


        for course in course_list:

            x = course['scores']
            num100, num75, num50, num25 = x['100'] + 1, x['75'] + 1, x['50'] + 1, x['25'] + 1

            # accuired_score = sum([num100 * 100, num75 , num50, num25])
            # division error

            expected_score = sum([num100, num75, num50, num25])
            print(expected_score)

            data100.append( calc_per(expected_score, num100) )
            data75.append( calc_per(expected_score, num75) )
            data50.append( calc_per(expected_score, num50) )
            data25.append( calc_per(expected_score, num25) )
            _course.append(course['course'])

        data[f"level{level['level']}"] = {
                                "title": title,
                                "courses": _course,
                                "data100": data100, 
                                "data75": data75, 
                                "data50": data50, 
                                "data25": data25, 
                                }

    print(data, course_list)
    
    return jsonify(data)




    

website/templates/includes/_csslinks.html
 <!-- BEGIN VENDOR CSS-->
 <link rel="stylesheet" type="text/css" href="../static/app-assets/css/bootstrap.css">
 <!-- font icons-->
 <link rel="stylesheet" type="text/css" href="../static/app-assets/fonts/icomoon.css">
 <link rel="stylesheet" type="text/css" href="../static/app-assets/fonts/flag-icon-css/css/flag-icon.min.css">
 <link rel="stylesheet" type="text/css" href="../static/app-assets/vendors/css/extensions/pace.css">
 <!-- END VENDOR CSS-->
 <!-- BEGIN ROBUST CSS-->
 <link rel="stylesheet" type="text/css" href="../static/app-assets/css/bootstrap-extended.css">
 <link rel="stylesheet" type="text/css" href="../static/app-assets/css/app.css">
 <link rel="stylesheet" type="text/css" href="../static/app-assets/css/colors.css">
 <!-- END ROBUST CSS-->
 <!-- BEGIN Page Level CSS-->
 <link rel="stylesheet" type="text/css" href="../static/app-assets/css/core/menu/menu-types/vertical-menu.css">
 <link rel="stylesheet" type="text/css" href="../static/app-assets/css/core/menu/menu-types/vertical-overlay-menu.css">
 <link rel="stylesheet" type="text/css" href="../static/app-assets/css/core/colors/palette-gradient.css">
 <!-- END Page Level CSS-->
 <!-- BEGIN Custom CSS-->
 <link rel="stylesheet" type="text/css" href="../static/assets/css/style.css">
 <!-- END Custom CSS-->
 <link rel="stylesheet" type="text/css" href="../static/css/toastr.css">

website/templates/includes/_footer.html
<footer class="navbar-bottom pt-1 pb-1 mx-100 navbar-border">
	<p class="clearfix text-muted text-sm-center mb-0 px-2">
		<span class="float-md-left d-xs-block d-md-inline-block"
			>Copyright &copy; <span id="year"></span>
			<a href="#" target="_blank" class="text-bold-800 grey darken-2"
				>KPT LABS </a
			>, All rights reserved. </span
		><span class="float-md-right d-xs-block d-md-inline-block"
			>Hand-crafted & Made with <i class="icon-heart5 pink"></i
		></span>
	</p>
</footer>

<script>
	var d = new Date();
	document.getElementById("year").innerHTML = d.getFullYear();
</script>

website/templates/includes/_navbar_index.html
<!-- navbar-fixed-top-->
<nav class=" header-navbar navbar navbar-with-menu navbar-fixed-top navbar-semi-dark navbar-shadow">
	<div class="navbar-wrapper">
		<div class="navbar-header">
			<ul class="nav navbar-nav">
				<li class="nav-item">
					<a href="index.html" class="navbar-brand nav-link"><img alt="branding logo"
							src="../static/app-assets/images/logo/robust-logo-light.png"
							data-expand="../static/app-assets/images/logo/robust-logo-light.png"
							data-collapse="../static/app-assets/images/logo/robust-logo-small.png" class="brand-logo" /></a>
				</li>
				<li class="nav-item hidden-md-up float-xs-right">
					<a data-toggle="collapse" data-target="#navbar-mobile" class="nav-link open-navbar-container"><i
							class="icon-ellipsis pe-2x icon-icon-rotate-right-right"></i></a>
				</li>
			</ul>
		</div>

		<div class="navbar-container content container-fluid ">
			<div id="navbar-mobile" class="collapse navbar-toggleable-sm">
				<ul class="nav navbar-nav float-xs-right mb-1 ">
					
					<li class="nav-item">
						<li class="nav-item">
							<a href="/about" class="btn  upgrade-to-pro">About</a>
						</li>
					</li>

					<li class="nav-item">
						<li class="nav-item">
							<a href="/contact" class="btn  upgrade-to-pro">Contact Us</a>
						</li>
					</li>

					<li class="nav-item">
						<li class="nav-item ">
							<a href="{{url_for('auth.login')}}"  class="btn btn-success text-bold upgrade-to-pro">Login</a>
						</li>
					</li>

					<li class="nav-item">
						<li class="nav-item pl-1">
							<a href="{{url_for('auth.register')}}"  class="btn btn-secondary text-bold upgrade-to-pro">Register</a>
						</li>
					</li>


				</ul>
			</div>
		</div>
	</div>
</nav>

<!-- ////////////////////////////////////////////////////////////////////////////-->

website/templates/includes/_sidebar.html
<!-- main menu-->
<div
	data-scroll-to-active="true"
	class="main-menu menu-fixed menu-dark menu-accordion menu-shadow"
>
	<!-- main menu header-->
	<div class="main-menu-header">
		<input
			type="text"
			placeholder="Search"
			class="menu-search form-control round"
		/>
	</div>
	<!-- / main menu header--M.a
	<!-- main menu content-->
	<div class="main-menu-content">
		<ul
			id="main-menu-navigation"
			data-menu="menu-navigation"
			class="navigation navigation-main"
		>
			<li class="nav-item">
				<a href="/dashboard">
					<i class="icon-grid2"></i>
					<span data-i18n="nav.dash.main" class="menu-title">Dashboard</span>
				</a>
			</li>

			<!-- #################  Student Start ################# -->
			<!-- #################  Student End ################# -->
			
			<!-- #################  Lecturer Start ################# -->
			<!-- #################  Lecturer End ################# -->
			
			<!-- #################  Admin Start ################# -->
			{% if session.usertype == 'admin' %}
				<li class="nav-item">
					<a href="{{ url_for('views.manage_courses') }}">
						<i class="icon-book"></i>
						<span data-i18n="nav.page_layouts.main" class="menu-title"
							>Courses</span
						>
					</a>
				</li>

				<li class="nav-item">
					<a href="{{ url_for('views.manage_lecturers') }}">
						<i class="icon-user-tie"></i>
						<span data-i18n="nav.project.main" class="menu-title"> Lecturers</span>
					</a>
				</li>

				<li class="nav-item">
					<a href="{{ url_for('views.evaluation_result') }}">
						<i class="icon-pie-chart"></i>
						<span data-i18n="nav.cards.main" class="menu-title">Evaluation Result</span>
					</a>
				</li>

				<li class="nav-item">
					<a href="{{ url_for('views.manage_students') }}">
						<i class="icon-users"></i>
						<span data-i18n="nav.advance_cards.main" class="menu-title"
							>Students</span
						>
					</a>
				</li>

				<li class="nav-item">
					<a href="#">
						<i class="icon-newspaper"></i>
						<span data-i18n="nav.content.main" class="menu-title">News</span>
					</a>
				</li>

				<li class="nav-item">
					<a href="#">
						<i class="icon-speech-bubble"></i>
						<span data-i18n="nav.components.main" class="menu-title"
							>FAQ Forum</span
						>
					</a>
				</li>

				<li class="nav-item">
					<a href="#">
						<i class="icon-cloud-download3"></i>
						<span data-i18n="nav.icons.main" class="menu-title">Downloads</span>
					</a>
				</li>

				<li class="nav-item">
					<a href="{{ url_for('views.settings') }}">
						<i class="icon-cog2"></i>
						<span
							data-i18n="nav.form_layouts.form_layout_basic"
							class="menu-title"
							>Settings</span
						>
					</a>
				</li>
			{% endif %}
			<!-- #################  Admin End ################# -->
			<li class="navigation-header">
				<span data-i18n="nav.category.support">Support</span>
				<i
					data-toggle="tooltip"
					data-placement="right"
					data-original-title="Support"
					class="icon-ellipsis icon-ellipsis"
				></i>
			</li>

			<li class="nav-item">
				<a
					href="https://github.com/pixinvent/robust-free-bootstrap-admin-template/issues"
				>
					<i class="icon-support"></i>
					<span data-i18n="nav.support_raise_support.main" class="menu-title"
						>Raise Support</span
					>
				</a>
			</li>

			<li class="nav-item">
				<a
					href="https://pixinvent.com/free-bootstrap-template/robust-lite/documentation"
				>
					<i class="icon-document-text"></i>
					<span data-i18n="nav.support_documentation.main" class="menu-title"
						>Documentation</span
					>
				</a>
			</li>
		</ul>
	</div>
	<!-- /main menu content-->
	<!-- main menu footer-->
	<!-- include includes/menu-footer-->
	<!-- main menu footer-->
</div>
<!-- / main menu-->

website/templates/includes/edit_student_modal.html
<!-- Modal -->
<div class="modal fade text-xs-left" id="editModal{{student['regnumber']}}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel2" aria-hidden="true">
  <div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <h4 class="modal-title" id="myModalLabel2"> Enter details to add student</hh4>
    </div>
    <div class="modal-body">
      
      <form
									class="form-horizontal form-simple"
									method="post"
									action="{{ url_for('auth.update_student')}}"
								>
									<div style="margin-top: 0px">
									</div>

									<input type="hidden" name="_id" value="{{ student['_id'] }}" />

									<div class="row">
										<!-- firstname -->
										<fieldset
											class="form-group position-relative has-icon-left mb-1 col-md-4"
										>
											<input
												type="text"
												class="form-control input-md"
												name="firstname"
												autocomplete="off"
												autofocus
												placeholder="First Name"
												value="{{student['firstname']}}"
												required
											/>
											<div class="form-control-position">
												<i class="icon-head"></i>
											</div>
										</fieldset>

										<!-- lastname -->
										<fieldset
											class="form-group position-relative has-icon-left mb-1 col-md-4"
										>
											<input
												type="text"
												class="form-control input-md"
												name="lastname"
												autocomplete="off"
												placeholder="Last Name"
												value="{{student['lastname']}}"
												required
											/>
											<div class="form-control-position">
												<i class="icon-user"></i>
											</div>
										</fieldset>

										<!-- reg number -->
										<fieldset
											class="form-group position-relative has-icon-left mb-1 col-md-4"
										>
											<input
												type="text"
												class="form-control input-md"
												name="regnumber"
												autocomplete="off"
												autofocus
												placeholder="Registration Number"
												value="{{student['regnumber']}}"
												required
											/>
											<div class="form-control-position">
												<i class="icon-ios-barcode"></i>
											</div>
										</fieldset>
									</div>

									<div class="row">
										<!-- level -->
										<fieldset
											class="form-group position-relative has-icon-left mb-1 col-md-4"
										>
											<select
												id="projectinput6"
												required
												name="level"
												class="form-control"
											>
												<option disabled="">Class</option>
												{% for i in levels %} 
													{% if i['level'] == student['level'] %}
														<option selected="selected" value="{{i['level']}}">{{ i['level'].title() }}  - {{ i['class'].title() }}</option>
													{% else %}
														<option value="{{i['level']}}">{{ i['level'].title() }}  - {{ i['class'].title() }}</option>
													{% endif %}
												{% endfor %}
											</select>
											<div class="form-control-position">
												<i class="icon-building"></i>
											</div>
										</fieldset>

										<!-- phone -->
										<fieldset
											class="form-group position-relative has-icon-left mb-1 col-md-4"
										>
											<input
												type="text"
												class="form-control input-md"
												name="phone"
												autocomplete="off"
												placeholder="Phone Number"
												value="{{student['phone']}}"
												required
											/>
											<div class="form-control-position">
												<i class="icon-phone"></i>
											</div>
										</fieldset>

										<!-- email -->
										<fieldset
											class="form-group position-relative has-icon-left mb-1 col-md-4"
										>
											<input
												type="email"
												class="form-control input-md"
												name="email"
												autocomplete="off"
												auto
												placeholder="Email"
												value="{{student['email']}}"
												required
											/>
											<div class="form-control-position">
												<i class="icon-email"></i>
											</div>
										</fieldset>
									</div>

									<div class="row">
										<!-- password -->
										<fieldset
											class="form-group position-relative has-icon-left mb-1 col-md-4"
										>
											<input
												type="text"
												class="form-control input-md"
												name="password"
												autocomplete="off"
												placeholder="Enter Password"
												required
												value="{{student['password']}}"
											/>
											<div class="form-control-position">
												<i class="icon-key3"></i>
											</div>
										</fieldset>

										<!-- confirm password -->
										<fieldset
											class="form-group position-relative has-icon-left mt-0 col-md-4"
										>
											<input
												type="text"
												class="form-control input-md"
												name="cpassword"
												autocomplete="off"
												placeholder="Confirm Password"
												required
												value="{{student['password']}}"
											/>
											<div class="form-control-position">
												<i class="icon-key3"></i>
											</div>
										</fieldset>
									</div>

									

									<button
										type="submit"
										class="btn btn-primary btn-lg btn-block"
									>
										<i class="icon-save"></i> Update
									</button>
								</form>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn grey btn-outline-secondary" data-dismiss="modal">Close</button>
    </div>
  </div>
  </div>
</div>